platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
- name: source-code

outputs:
- name: build-output

run:
  path: bash
  args: [ source-code/ci/tasks/deploy.sh ]