groups:
- name: main
  jobs:
  - unit-test
  - package
  - deploy


resources:
- name: source-code
  type: git
  check_every: 10s
  source:
    uri: https://github.com/txt8888/hello-world.git
    branch: master

jobs:
- name: unit-test
  serial: true
  public: true
  plan:
  - get: source-code
    trigger: true
  - task: unit-test
    file: source-code/ci/tasks/test.yml

- name: package
  serial: true
  public: true
  plan:
  - get: source-code
    trigger: true
    passed:
    - unit-test
  - task: package
    file: source-code/ci/tasks/package.yml

- name: deploy
  serial: true
  public: true
  plan:
  - get: source-code
    trigger: true
    passed:
    - package
  - task: deploy
    file: source-code/ci/tasks/deploy.yml