resources:
- name: source-code
  type: git
  check_every: 10s
  source:
    uri: https://github.com/txt8888/hello-world.git
    branch: master

jobs:
- name: list
  serial: true
  plan:
  - get: source-code
    trigger: true
  - task: list-files
    privileged: true
    file: source-code/ci/tasks/ls.yml

- name: unit-test
  serial: true
  plan:
  - task: unit-test
    privileged: true
    file: source-code/ci/tasks/test.yml


- name: package
  serial: true
  plan:
  - task: package
    privileged: true
    file: source-code/ci/tasks/package.yml

- name: deploy
  serial: true
  plan:
  - task: deploy
    privileged: true
    file: source-code/ci/tasks/deploy.yml