resources:
- name: source-code
  type: git
  check_every: 10s
  source:
    uri: https://github.com/txt8888/hello-world.git
    branch: master

jobs:
- name: list-files
  plan:
  - get: source-code
    trigger: true
  - task: list-files
    file: source-code/ci/tasks/ls.yml

- name: unit-test
  plan:
  - task: unit-test
    file: source-code/ci/tasks/test.yml

- name: package
  plan:
  - task: package
    file: source-code/ci/tasks/package.yml

- name: deploy
  plan:
  - task: deploy
    file: source-code/ci/tasks/deploy.yml